name: .NET Core

on: [ push ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Installing dependencies
      run: dotnet restore
    - name: Building
      run: dotnet build --configuration Release --no-restore
    - name: Testing
      run: |
        dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[xunit*]\*" /p:CoverletOutput="./TestResults/"
        cd XUnit.Coverlet.Collector
        dotnet reportgenerator "-reports:TestResults/coverage.cobertura.xml" "-targetdir:TestResults/html" -reporttypes:HTML;
        dotnet reportgenerator "-reports:TestResults/coverage.cobertura.xml" "-targetdir:TestResults/txt" -reporttypes:TextSummary;
        value=$(<TestResults/txt/Summary.txt)
        echo "$value"
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: XUnit.Coverlet.Collector/TestResults
    - name: dotnet-format
      run: |
        dotnet tool install -g dotnet-format
        dotnet-format --check || exit 1
    - name: Add commit comment
      run: |
        jq -nc '{"body": $value}' | \
        curl -sL  -X POST -d @- \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments"
