name: .NET Core

on: [ push ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Installing dependencies
      run: dotnet restore
    - name: Building
      run: dotnet build --configuration Release --no-restore
    - name: Testing
      run: dotnet test
    - name: dotnet-format
      run: |
        dotnet tool install -g dotnet-format
        dotnet-format --check || exit 1
